import Head from "next/head";

import Nav from "../../components/Nav";
import { User as UserContent } from "../../components/User";
import { Octokit } from '@octokit/rest';


export async function getServerSideProps({ query }) {
  
  const res = await fetch(`https://api.github.com/users/${query.name}`, {
    headers: {
      Authorization: "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",
      "Content-Type": "application/json",
      Accept: "application/json",
    },
  });
  const data = await res.json();

  if (!data) {
    return {
      notFound: true,
    };
  }

  return {
    props: {
      user: data,
    },
  };
}

export default function Name({ user }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,300;0,500;0,700;1,300;1,400;1,500;1,700&display=swap"
          rel="stylesheet"
        />
      </Head>
      <main>
        <Nav isHome={false} />
        <UserContent user={user} />
      </main>
    </>
  );
}
