import Head from "next/head";

import Nav from "../../components/Nav";
import { User as UserContent } from "../../components/User";
import { Octokit } from '@octokit/rest';


export async function getServerSideProps({ query }) {

  const octokit = new Octokit({
    auth: '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'
  })

  const res = await octokit.request(`GET /users/${query.name}`, {
    username: query.name,
    headers: {
      'X-GitHub-Api-Version': '2022-11-28'
    }
  })
  
  const data = await res.data;

  if (!data) {
    return {
      notFound: true,
    };
  }

  return {
    props: {
      user: data,
    },
  };
}

export default function Name({ user }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,300;0,500;0,700;1,300;1,400;1,500;1,700&display=swap"
          rel="stylesheet"
        />
      </Head>
      <main>
        <Nav isHome={false} />
        <UserContent user={user} />
      </main>
    </>
  );
}
